### ISSUE TITLE
EggBorn.js Tutorial | EggBorn.js | The Ultimate Javascript Full Stack Framework

### ISSUE THREAD

**Issue by zhennann** [zhennann/egg-born#2]
http://egg-born.org/en/docs/tutorial/

**Comment by zhennann** [comment]
Welcome to here!

**Comment by jeffycai** [comment]
very nice

**Comment by arronf2e** [comment]
很不错

**Comment by mengxiaof** [comment]
为何安装不上依赖的包

**Comment by zhennann** [comment]
@mengxiaof 请贴出具体的操作与提示。

**Comment by InMicroFish** [comment]
按照步骤一步一步下来没问题
npm run dev:backend
npm run dev:front

之后主动弹出 127.0.0.1:9092  一直卡住  出不了界面 咋回事？

**Comment by InMicroFish** [comment]
npm run build:front

一直卡在这
/ building for production...

**Comment by zhennann** [comment]
麻烦提供以下信息：
1、node版本号
2、使用的npm，还是其他包管理工具，版本号
3、操作系统

**Comment by InMicroFish** [comment]
node v8.9.1
npm 5.5.1
OS  win10  v15063.674

**Comment by zhennann** [comment]
使用你提供的环境运行正常。可否远程排查。

**Comment by InMicroFish** [comment]
我再试试

**Comment by InMicroFish** [comment]
mysql 的database  一定要是egg-born么

**Comment by zhennann** [comment]
database‘s name可以改成你需要的。

**Comment by InMicroFish** [comment]
PS F:\InMicro-SVN-back\Engineer\Application\InMicroWeb\InMicroNodejs\born-example> snpm i

> uglifyjs-webpack-plugin@0.4.6 postinstall F:\InMicro-SVN-back\Engineer\Application\InMicroWeb\InMicroNodejs\born-example\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN co-mocha@1.2.1 requires a peer of mocha@>=1.18 <5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1590 packages in 229.644s

**Comment by InMicroFish** [comment]
可以了   虽然有以上warn    还是可以   之前不行可能是npm install  不对么？

**Comment by zhennann** [comment]
我看你使用的是“snpm”。建议使用原生npm，搭配淘宝镜像即可。
你前面出现的卡住的情况，很有可能是某些包依赖有问题。

**Comment by InMicroFish** [comment]
ok 谢谢

**Comment by zhennann** [comment]
with pleasure

**Comment by callmesoul** [comment]
Restful api 架构权限控制是个难题，希望后续有封装好

**Comment by zhennann** [comment]
@callmesoul right, may you have any suggestions?

**Comment by mengxiaof** [comment]
怎么通过pm2 管理这个项目

**Comment by mengxiaof** [comment]
如果使用pm2 区管理这个项目

**Comment by callmesoul** [comment]
@mengxiaof 应该是参考egg

**Comment by zhennann** [comment]
> 可以参考[https://eggjs.org/zh-cn/faq.html#进程管理为什么没有选型-pm2](https://eggjs.org/zh-cn/faq.html#进程管理为什么没有选型-pm2)

> 建议直接使用eggjs提供的多进程管理模型，不过仍然可以使用pm2管理。在EggBorn.js中如下配置：

1. 在项目根目录添加文件server.js
```javascript
const egg = require('egg');
const path = require('path');

const workers = Number(process.argv[2] || require('os').cpus().length);
egg.startCluster({
  workers,
  baseDir: path.join(__dirname, 'src/backend/'),
});
``` 
2. 命令行执行
```bash
$ pm2 start server.js
```
