### ISSUE TITLE
Recommend MongoDB rather than MySQL for 'Full-Stack JavaScript'

### ISSUE THREAD

**Issue by tonghuashuo** [zhennann/egg-born#3]
For 'Full-Stack JavaScript', I assume everything should be using JavaScript as long as it's possible. Hence MongoDB would be a better choice rather than MySQL under this topic. (Though I understand these two serves different cases.)

**Comment by zhennann** [comment]
EggBorn.js built-in mysql, so as to achieve a more convenient transaction management.
EggBorn.js still allows the use of other databases such as MongoDB. 
EggBorn.js backend based on Egg.js, so you can get more infomation from here: [egg-mongoose](https://github.com/eggjs/egg-mongoose)
